from enum import Enum

class DoctorSpecialization(str, Enum):
    GENERAL_PHYSICIAN = "GENERAL_PHYSICIAN"
    CARDIOLOGIST = "CARDIOLOGIST"
    DERMATOLOGIST = "DERMATOLOGIST"
    NEUROLOGIST = "NEUROLOGIST"
    ORTHOPEDIC = "ORTHOPEDIC"
    PEDIATRICIAN = "PEDIATRICIAN"
    GYNECOLOGIST = "GYNECOLOGIST"
    PSYCHIATRIST = "PSYCHIATRIST"
    ENT = "ENT"
    OPHTHALMOLOGIST = "OPHTHALMOLOGIST"